sonar.organization=nikon11211
sonar.projectKey=nikon11211_postgresql-connector
sonar.projectName=postgresql-connector
sonar.sources=.
sonar.exclusions=**/*_test.go,examples/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.coverage.exclusions=examples/**/*
